SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."1S_implementations_all" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "date" "date",
    "order_id" "text",
    "product_name" "text",
    "delivery_method" "text",
    "warehouce" bigint,
    "category1" "text",
    "category2" "text",
    "category3" "text",
    "category4" "text",
    "quantity" bigint,
    "total" bigint,
    "order_hour" "text"
);

ALTER TABLE "public"."1S_implementations_all" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."1S_orders_all" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "date" "date",
    "order_id" "text",
    "product_name" "text",
    "delivery_method" "text",
    "warehouce" bigint,
    "category1" "text",
    "category2" "text",
    "category3" "text",
    "category4" "text",
    "quantity" bigint,
    "total" bigint,
    "order_hour" "text"
);

ALTER TABLE "public"."1S_orders_all" OWNER TO "postgres";

ALTER TABLE "public"."1S_orders_all" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."1S_orders_all_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE "public"."1S_implementations_all" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."1С_Implementations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."warehouse" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "long" "text",
    "lat" "text"
);

ALTER TABLE "public"."warehouse" OWNER TO "postgres";

ALTER TABLE "public"."warehouse" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."warehouse_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."1S_orders_all"
    ADD CONSTRAINT "1S_orders_all_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."1S_implementations_all"
    ADD CONSTRAINT "1С_Implementations_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."warehouse"
    ADD CONSTRAINT "warehouse_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."1S_implementations_all"
    ADD CONSTRAINT "1S_implementations_all_warehouce_fkey" FOREIGN KEY ("warehouce") REFERENCES "public"."warehouse"("id");

ALTER TABLE ONLY "public"."1S_orders_all"
    ADD CONSTRAINT "1S_orders_all_warehouce_fkey" FOREIGN KEY ("warehouce") REFERENCES "public"."warehouse"("id");

ALTER TABLE "public"."1S_implementations_all" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."1S_orders_all" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."warehouse" ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."1S_implementations_all" TO "anon";
GRANT ALL ON TABLE "public"."1S_implementations_all" TO "authenticated";
GRANT ALL ON TABLE "public"."1S_implementations_all" TO "service_role";

GRANT ALL ON TABLE "public"."1S_orders_all" TO "anon";
GRANT ALL ON TABLE "public"."1S_orders_all" TO "authenticated";
GRANT ALL ON TABLE "public"."1S_orders_all" TO "service_role";

GRANT ALL ON SEQUENCE "public"."1S_orders_all_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."1S_orders_all_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."1S_orders_all_id_seq" TO "service_role";

GRANT ALL ON SEQUENCE "public"."1С_Implementations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."1С_Implementations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."1С_Implementations_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."warehouse" TO "anon";
GRANT ALL ON TABLE "public"."warehouse" TO "authenticated";
GRANT ALL ON TABLE "public"."warehouse" TO "service_role";

GRANT ALL ON SEQUENCE "public"."warehouse_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."warehouse_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."warehouse_id_seq" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;